name: Deploy Prowler

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose a runner. Here, we use the latest Ubuntu version

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2  # This step checks out your repository

    - name: Deploy Prowler
      run: make prowler  # Run the deployment command

