name: Deploy Prowler

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Deploy Prowler
      run: make prowler

    - name: Get container name
      run: docker ps -a

    - name: Copy output from container
      run: |
        docker cp $(docker ps -aq --latest):/home/prowler/output ./output

    - name: Set timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Prowler-${{ env.TIMESTAMP }}
        path: ./output/*

